### ISSUE TITLE
Problem execution with import library libglib-2.0.so.0 and libgthread-2.0.so.0 for opencv

### ISSUE THREAD

**Issue by MickaelStipe79** [horihiro/azure-functions-python-opencv-example#3]
Hello,
I am neither an expert in python nor in azure. I followed the tutorial successfully until copying lib: libglib-2.0.so.0 and libgthread-2.0.so.0 created on Windows with Docker. By cons when I run the project (F5 on Visual Studio Code) I get these errors. I do not know what to do. Can anyone help?

![Github-bug01](https://user-images.githubusercontent.com/8004476/141753538-342e7c0f-4be0-4398-adaf-73fc77bf17bb.png)

**Comment by horihiro** [comment]
It seems that you are trying to import `.so` on **Windows**. Windows cannot load `.so` file which is the shared object file for Unix/Linux. If you want to debug with VSCode, you should use devContainer.

**Comment by MickaelStipe79** [comment]
Thank for your response. When I comment the two lines for loading the libraries, it works well.
